#!/bin/bash

# myBackup: PWD Backup utility by yd0369

BACKUP_SAVE_PATH=$(pwd)

DATE=$(date +%d%m%Y)

BACKUP_PREFIX="pwd_backup_"
BACKUP_EXT=".tar"

FILE_NAME=$BACKUP_SAVE_PATH/$BACKUP_PREFIX$DATE$BACKUP_EXT

tar cfz $FILE_NAME $BACKUP_SAVE_PATH

echo "MADE BACKUP : "$FILE_NAME


