#!/bin/bash

# myBackup: PWD Backup utility by yd0369

BACKUP_SAVE_PATH=$(pwd)

DATE=$(date +%d%m%Y)

BACKUP_PREFIX="pwd_backup_"
BACKUP_EXT=".tar"

FILE_NAME=$BACKUP_SAVE_PATH/$BACKUP_PREFIX$DATE$BACKUP_EXT

tar cfz $FILE_NAME $BACKUP_SAVE_PATH

echo "MADE BACKUP : "$FILE_NAME

if test -f "$FILE_NAME"; then
    echo "Backup Successful && Email Sent" | mail -s "Backup Successful" yd0369@github.com
else
    echo $DATE "Backup Failed : Error in making backup" >> $BACKUP_SAVE_PATH/backup.log 
fi
